### ISSUE TITLE
Exploring Agent - Automated Testing Plan

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#101]
Automated Testing Plans are due by the Spring Relay.

Please submit your plan in your team folder: https://drive.google.com/drive/folders/1wH2njrx6ICjRh879WAfh3UgWKuXLv0os?usp=sharing

The Program Milestone reads:
An automated testing plan to verify service availability and basic knowledge retrieval has been developed for each Translator tool [your team maintains], with detailed documentation on the expected results of each test.

@NCATSTranslator/exploring-agent

**Comment by andrewsu** [comment]
adding link to our nascent regression testing framework https://github.com/biothings/bte_regression_test

**Comment by ariutta** [comment]
To track my progress on this, please check the issues in the bte_regression_test repo:
https://github.com/biothings/bte_regression_test/issues

**Comment by andrewsu** [comment]
Our final document is now in this gdoc https://docs.google.com/document/d/1pGdmMgI-LzOlzcdoGPvLS3KDvyHtRjECJ6wF0LMqI64/edit, which is located in our team folder.
