### ISSUE TITLE
Expander Agent - Automated Testing Plan

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#103]
Automated Testing Plans are due by the Spring Relay.

Please submit your plan in your team folder: https://drive.google.com/drive/folders/1wH2njrx6ICjRh879WAfh3UgWKuXLv0os?usp=sharing

The Program Milestone reads:
An automated testing plan to verify service availability and basic knowledge retrieval has been developed for each Translator tool [your team maintains], with detailed documentation on the expected results of each test.

@NCATSTranslator/expander-agent

**Comment by saramsey** [comment]
OK, the [testing plan](https://drive.google.com/file/d/1ax31qv6aTbAAjJtN4_klB1HMxUIQsOrW/view?usp=sharing) is in the Google Drive. If anything looks amiss, we'd be grateful if NCATS could let us know, and we will be sure to fix it before the relay. 

<img width="898" alt="Screen Shot 2021-05-06 at 9 48 12 PM" src="https://user-images.githubusercontent.com/5562107/117399205-df61b180-aeb4-11eb-9e69-557054d68d8a.png">
