### ISSUE TITLE
SRI - Verify Server Info

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#109]
Can you please verify what we have for SRI on: https://github.com/NCATSTranslator/TranslatorPM/blob/main/Translator%20Server%20Info.md

If there are tools we are missing, please let us know.

@NCATSTranslator/sri

**Comment by tursynay** [comment]
@patrickkwang, I asked Chris B and he said that this looks good but asked to run this by you. Would you take a look and let us know? https://github.com/NCATSTranslator/TranslatorPM/blob/main/Translator%20Server%20Info.md

**Comment by patrickkwang** [comment]
@cbizon What is the status of bl-lookup.sri.renci.org? I could not figure out how to reach it?

**Comment by cbizon** [comment]
Looks like the URL is wrong, should be: https://bl-lookup-sri.renci.org/apidocs/
