### ISSUE TITLE
Exposures - Verifying the TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#112]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing).  You are currently listed as the representative for Exposures - do you represent both ICCES+ and CAM?

**Comment by sstemann** [comment]
@stevencox Just checking if you've had a chance to verify the TRAPI WG roster, it's optional but we're wanting to make sure that when TRAPI WG tags reviewers the notifications are going to the right folks.  Thanks!

**Comment by stevencox** [comment]
Hi @sstemann, I represent ICEES+.

**Comment by sstemann** [comment]
thanks!
