### ISSUE TITLE
Exploring Agent, Service Provider - Verifying the TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#113]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing).  You are currently listed as the representative for Exploring Agent/Service Provider is that current?  If not, can you please make the updates to the roster or let us know here?

**Comment by andrewsu** [comment]
We haven't been regular attendees at the TRAPI WG meetings.  We've found that our teams have generally been fine adapting to whatever TRAPI requirements are adopted, so we've been focusing on other WGs.  But if our more active participation is needed for reasons I've missed, please let me know... Thanks!

**Comment by sstemann** [comment]
Not at all, just updating the roster so we can tag folks as needed as they process through the v1.1 PRs.  Thanks!
