### ISSUE TITLE
Unsecret Agent - Verifying the TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#114]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing). You are currently listed as the representative for Unsecret is that current? If not, can you please make the updates to the roster or let us know here?

**Comment by gregr** [comment]
Did you mean to assign this to @webyrd ?

**Comment by gregr** [comment]
Oh, I found it.  I updated the roster.

**Comment by sstemann** [comment]
Thanks!
