### ISSUE TITLE
CHP - Verifying the TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#116]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing). You are currently listed as the representative for Connections Hypothesis Provider is that current? If not, can you please make the updates to the roster or let us know here?

**Comment by sstemann** [comment]
@yakaboskic @NCATSTranslator/connections-hypotheses-provider  Just checking if you've had a chance to verify the TRAPI WG roster, it's optional but we're wanting to make sure that when TRAPI WG tags reviewers the notifications are going to the right folks.  Thanks!

**Comment by yakaboskic** [comment]
@sstemann Yes, this is current and I am the rep. Thank you!
