### ISSUE TITLE
Multiomics - Verifying the TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#117]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing). You are currently listed as the representative for Multiomics Provider is that current? If not, can you please make the updates to the roster or let us know here?

**Comment by rtroper** [comment]
@sstemann - Yes, from our group, that would be me.

**Comment by sstemann** [comment]
Thanks!
