### ISSUE TITLE
Text Mining - Verifying the TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#118]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing). You are currently listed as the representative for Text Mining Provider is that current? If not, can you please make the updates to the roster or let us know here?

**Comment by sstemann** [comment]
@bill-baumgartner just checking if this is accurate.  It's optional for a WG but just want to make sure that when they tag reviewers, the notifications are going to the right folks.  Thanks!

**Comment by bill-baumgartner** [comment]
Sorry for not seeing this earlier. Yes, I am still the Text Mining Provider rep for the TRAPI WG.
