### ISSUE TITLE
CDSP - Verifying TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#119]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing). You are currently listed as the representative for Clinical Data Services Provider is that current? If not, can you please make the updates to the roster or let us know here?

**Comment by CaseyTa** [comment]
Hi @sstemann, yes, I'm the current representative on TRAPI. I've updated the roster. Thanks.

**Comment by sstemann** [comment]
Thanks!
