### ISSUE TITLE
Expander - Verifying TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#120]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing). You are currently listed as the representative for Expander is that current? If not, can you please make the updates to the roster or let us know here?

**Comment by amykglen** [comment]
I'm more of a very occasional attendee, so I just removed myself from the list. :) Eric Deutsch is Expander Agent's representative, and I see he's listed on there. so I think all looks good now!

**Comment by sstemann** [comment]
Thanks!
