### ISSUE TITLE
SRI - Verifying TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#121]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing). You are currently listed as the representative for SRI is that current? If not, can you please make the updates to the roster or let us know here?

**Comment by sstemann** [comment]
@RichardBruskiewich @kshefchek just checking if this is confirmed - totally optional but just want to make sure that when they tag reviewers we have the right list for notifications.  Thanks!

**Comment by kshefchek** [comment]
sorry for the slow response! I'm happy to rep for SRI on the TRAPI working group.

**Comment by sstemann** [comment]
thanks!
