### ISSUE TITLE
Explanatory Agent - Verifying TRAPI Roster

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#122]
We're verifying the roster for the TRAPI Working Group (https://docs.google.com/spreadsheets/d/1aY_p87Lnoi2BK1BUONPmRmr_-FwYGELYyqHKCGx0peE/edit?usp=sharing). 

Looks like xARA is not represented.  Its an optional working group, but just wanted to verify if you would like a rep included in this team.

@NCATSTranslator/explanatory-agent

**Comment by Rosinaweber** [comment]
Thanks, Sarah. Tom usually attends. Let me discuss it with the team. I appreciate you pointing us out to that.

**Comment by sstemann** [comment]
@Rosinaweber just checking - is Tom confirmed?  it's optional but just want to make sure when TRAPI WG requests votes we have the right reviewer.  Thanks!

**Comment by Rosinaweber** [comment]
Tom is confirmed.
