### ISSUE TITLE
OpenPredict/Collaboratory - Verify Server Info for Clinical Data Services

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#50]
Can you please verify what we have for your teams OpenPredict and Collaboratory tools on: https://github.com/NCATSTranslator/TranslatorPM/blob/main/Translator%20Server%20Info.md

Assigning to @vemonet based on SmartAPI registered by info, please redirect as needed.

Updated the table directly or add details here and assign back to Sarah Stemann.

**Comment by vemonet** [comment]
Hi @sstemann 

I updated the Knowledge Collaboratory API URL:

https://github.com/NCATSTranslator/TranslatorPM/compare/main...vemonet:patch-1
