### ISSUE TITLE
ICEES+ - Verify Server Info for Exposures Provider

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#55]
Can you please verify what we have for your team's ICEES+ on: https://github.com/NCATSTranslator/TranslatorPM/blob/main/Translator%20Server%20Info.md

Assigning to @xu-hao based on SmartAPI registered by info, please redirect as needed.

Update the table directly or add details here and assign back to Sarah Stemann.

**Comment by sstemann** [comment]
@mmersmann just checking if someone from ICEES+ can verify the server info?

**Comment by mmersmann** [comment]
@sstemann This looks right to me but @patrickkwang can verify for ICEES and @balhoff can verify for AOP/CAM.

**Comment by patrickkwang** [comment]
Looks good.
