### ISSUE TITLE
CAM - Verify Server Info for Exposures Provider

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#56]
Can you please verify what we have for your team's CAM Provider on: https://github.com/NCATSTranslator/TranslatorPM/blob/main/Translator%20Server%20Info.md

Assigning to @balhoff  based on SmartAPI registered by info, please redirect as needed.

Update the table directly or add details here and assign back to Sarah Stemann.

**Comment by balhoff** [comment]
@sstemann that address is correct.
