### ISSUE TITLE
Genetics Provider - Verify Server Info

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#57]
Can you please verify what we have for the Genetics Provider on: https://github.com/NCATSTranslator/TranslatorPM/blob/main/Translator%20Server%20Info.md

Assigning to @marcdubybroad based on SmartAPI registered by info, please redirect as needed.

Update the table directly or add details here and assign back to Sarah Stemann.

**Comment by marcdubybroad** [comment]
I submitted a pull request a few days ago; unclear if ti made it through.
Just in case it didn't, the genetics KP server address is now:
https://translator.broadinstitute.org/genetics_provider/trapi/v1.0

**Comment by marcdubybroad** [comment]
Updated data; closing issue.
