### ISSUE TITLE
MolePro - Verify Server Info

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#58]
Can you please verify what we have for the MolePro on: https://github.com/NCATSTranslator/TranslatorPM/blob/main/Translator%20Server%20Info.md

Assigning to @marcdubybroad based on Genetics Provider SmartAPI registered by info, please redirect as needed.

Update the table directly or add details here and assign back to Sarah Stemann.

**Comment by sstemann** [comment]
@marcdubybroad do you mind just verifying the info we have and confirming?  thanks!

**Comment by marcdubybroad** [comment]
Just submitted a pull request with the change. In case it didn't make it through, the molepro server address is:
https://translator.broadinstitute.org/molepro/trapi/v1.0

**Comment by marcdubybroad** [comment]
Closing
