### ISSUE TITLE
Aragorn and Automat - Verify Server Info 

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#61]
Can you please verify what we have for the Ranking Agent Tools on: https://github.com/NCATSTranslator/TranslatorPM/blob/main/Translator%20Server%20Info.md

Assigning to @patrickkwang  and @YaphetKG  based on SmartAPI registered by info, please redirect as needed.

Update the table directly or add details here and assign back to Sarah Stemann.

**Comment by patrickkwang** [comment]
I think GitHub failed auto-close this. @sstemann, is this good to close?
