### ISSUE TITLE
Text Mining - Verify Server Info

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#62]
We're trying to document our federated dev environment, I can't seem to get the server info from SmartAPI, could you take a look at the table here:

https://github.com/NCATSTranslator/TranslatorPM/blob/main/Translator%20Server%20Info.md

And either update directly in the markdown or update this ticket. We have the following KPs for your team:
- Cooccurrence KG
- Biolink Association KG
- Targeted Association KG
- Ontology KG

@NCATSTranslator/text-mining-provider  sorry to tag the whole team but I'm not sure who to work with to get these updates! Thanks for your help!

**Comment by bill-baumgartner** [comment]
Addressed in #82
