### ISSUE TITLE
Review/Update the How To: Announcements

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#86]
@NCATSTranslator/pm-maintainers i started a short guide in GitHub but it could really use your help and input - content and formatting!  please update the file as you see fit!

https://github.com/NCATSTranslator/TranslatorPM/blob/main/How%20to:%20%20Announcements.md

**Comment by nlharris** [comment]
Sorry about that--I was trying to add @mmersmann to the assignees but she doesn't seem to be in this organization.

**Comment by sstemann** [comment]
she's in the pending invite list on the members page.  i've tried re-inviting just now to see if that helps.

**Comment by mmersmann** [comment]
I'm in!  And have added myself as an assignee.

**Comment by sstemann** [comment]
closing this - but feel free to update the documentation as needed.  meant to be a living document.
