### ISSUE TITLE
Text Mining Provider - Automated Testing Plan

### ISSUE THREAD

**Issue by sstemann** [NCATSTranslator/TranslatorPM#97]
Automated Testing Plans are due by the Spring Relay.

Please submit your plan in your team folder: https://drive.google.com/drive/folders/1KIlgmSDHfCfCLWYCLMEQUmp0C-Q__o38?usp=sharing

The Program Milestone reads:
An automated testing plan to verify service availability and basic knowledge retrieval has been developed for each Translator tool [your team maintains], with detailed documentation on the expected results of each test.

@NCATSTranslator/text-mining-provider

**Comment by bill-baumgartner** [comment]
The Text Mining Provider Automated Testing Plan has been submitted [here](https://docs.google.com/document/d/1nOmPW7GvD09QsitBjaNdK3Lu_w3jf6kG2W58lFYKpD8/edit?usp=sharing). Closing this issue as I think it is now resolved. Thanks!
